using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.OData;
using CustomerOData.Models;

namespace SimpleOData.Controllers
{
    public class CustomersController : EntitySetController<Customer, int>
    {
        List<Customer> customers = new List<Customer>()
            { new Customer() { ID=1, LastName="Achongs", FirstName="Gustavo", EmailAddress="gustavo@adventure-works.com", Phone="398-555-0132" },
            new Customer() { ID=2, LastName="Abel", FirstName="Catherine", EmailAddress="catherine0@adventure-works.com", Phone="747-555-0171" },
            new Customer() { ID=3, LastName="Abercrombie", FirstName="Kim", EmailAddress="kim2@adventure-works.com", Phone="334-555-0137" },
            new Customer() { ID=4, LastName="Acevedo", FirstName="Humberto", EmailAddress="humberto0@adventure-works.com", Phone="599-555-0127" },
            new Customer() { ID=5, LastName="Ackerman", FirstName="Pilar", EmailAddress="pilar1@adventure-works.com", Phone="1 (11) 500 555-0132" },
            new Customer() { ID=6, LastName="Adams", FirstName="Frances", EmailAddress="frances0@adventure-works.com", Phone="991-555-0183" },
            new Customer() { ID=7, LastName="Smith", FirstName="Margaret", EmailAddress="margaret0@adventure-works.com", Phone="959-555-0151" },
            new Customer() { ID=8, LastName="Adams", FirstName="Carla", EmailAddress="carla0@adventure-works.com", Phone="107-555-0138" },
            new Customer() { ID=9, LastName="Adams", FirstName="Jay", EmailAddress="jay1@adventure-works.com", Phone="158-555-0142" },
            new Customer() { ID=10, LastName="Adina", FirstName="Ronald", EmailAddress="ronald0@adventure-works.com", Phone="453-555-0165" },
            new Customer() { ID=11, LastName="Agcaoili", FirstName="Samuel", EmailAddress="samuel0@adventure-works.com", Phone="554-555-0110" },
            new Customer() { ID=12, LastName="Aguilar", FirstName="James", EmailAddress="james2@adventure-works.com", Phone="1 (11) 500 555-0198" },
            new Customer() { ID=13, LastName="Ahlering", FirstName="Robert", EmailAddress="robert1@adventure-works.com", Phone="678-555-0175" },
            new Customer() { ID=14, LastName="Ferrier", FirstName="François", EmailAddress="françois1@adventure-works.com", Phone="571-555-0128" },
            new Customer() { ID=15, LastName="Akers", FirstName="Kim", EmailAddress="kim3@adventure-works.com", Phone="440-555-0166" },
            new Customer() { ID=16, LastName="Alameda", FirstName="Lili", EmailAddress="lili0@adventure-works.com", Phone="1 (11) 500 555-0150" },
            new Customer() { ID=17, LastName="Alberts", FirstName="Amy", EmailAddress="amy1@adventure-works.com", Phone="727-555-0115" },
            new Customer() { ID=18, LastName="Albright", FirstName="Anna", EmailAddress="anna0@adventure-works.com", Phone="197-555-0143" },
            new Customer() { ID=19, LastName="Albury", FirstName="Milton", EmailAddress="milton0@adventure-works.com", Phone="492-555-0189" },
            new Customer() { ID=20, LastName="Alcorn", FirstName="Paul", EmailAddress="paul2@adventure-works.com", Phone="331-555-0162" },
            new Customer() { ID=21, LastName="Alderson", FirstName="Gregory", EmailAddress="gregory0@adventure-works.com", Phone="968-555-0153" },
            new Customer() { ID=22, LastName="Alexander", FirstName="J. Phillip", EmailAddress="jphillip0@adventure-works.com", Phone="845-555-0187" },
            new Customer() { ID=23, LastName="Alexander", FirstName="Michelle", EmailAddress="michelle0@adventure-works.com", Phone="115-555-0175" },
            new Customer() { ID=24, LastName="Jacobson", FirstName="Sean", EmailAddress="sean2@adventure-works.com", Phone="555-555-0162" },
            new Customer() { ID=25, LastName="Allen", FirstName="Phyllis", EmailAddress="phyllis0@adventure-works.com", Phone="695-555-0111" },
            new Customer() { ID=26, LastName="Allen", FirstName="Marvin", EmailAddress="marvin0@adventure-works.com", Phone="447-555-0110" },
            new Customer() { ID=27, LastName="Allen", FirstName="Michael", EmailAddress="michael10@adventure-works.com", Phone="607-555-0193" },
            new Customer() { ID=28, LastName="Allison", FirstName="Cecil", EmailAddress="cecil0@adventure-works.com", Phone="699-555-0155" },
            new Customer() { ID=29, LastName="Alpuerto", FirstName="Oscar", EmailAddress="oscar0@adventure-works.com", Phone="855-555-0174" },
            new Customer() { ID=30, LastName="Altamirano", FirstName="Sandra", EmailAddress="sandra1@adventure-works.com", Phone="1 (11) 500 555-0190" },
            new Customer() { ID=31, LastName="Alvarado", FirstName="Selena", EmailAddress="selena0@adventure-works.com", Phone="781-555-0199" },
            new Customer() { ID=32, LastName="Alvaro", FirstName="Emilio", EmailAddress="emilio0@adventure-works.com", Phone="178-555-0129" },
            new Customer() { ID=33, LastName="Amland", FirstName="Maxwell", EmailAddress="maxwell0@adventure-works.com", Phone="614-555-0134" },
            new Customer() { ID=34, LastName="Anderson", FirstName="Mae", EmailAddress="mae0@adventure-works.com", Phone="1 (11) 500 555-0181" },
            new Customer() { ID=35, LastName="Antrim", FirstName="Ramona", EmailAddress="ramona0@adventure-works.com", Phone="327-555-0148" },
            new Customer() { ID=36, LastName="Appelbaum", FirstName="Sabria", EmailAddress="sabria0@adventure-works.com", Phone="922-555-0193" },
            new Customer() { ID=37, LastName="Arakawa", FirstName="Hannah", EmailAddress="hannah0@adventure-works.com", Phone="500-555-0134" },
            new Customer() { ID=38, LastName="Arbelaez", FirstName="Kyley", EmailAddress="kyley0@adventure-works.com", Phone="717-555-0131" },
            new Customer() { ID=39, LastName="Johnston", FirstName="Tom", EmailAddress="tom1@adventure-works.com", Phone="883-555-0177" },
            new Customer() { ID=40, LastName="Armstrong", FirstName="Thomas", EmailAddress="thomas1@adventure-works.com", Phone="226-555-0146" },
            new Customer() { ID=41, LastName="Arthur", FirstName="John", EmailAddress="john6@adventure-works.com", Phone="149-555-0113" },
            new Customer() { ID=42, LastName="Ashton", FirstName="Chris", EmailAddress="chris3@adventure-works.com", Phone="556-555-0145" },
            new Customer() { ID=43, LastName="Atkinson", FirstName="Teresa", EmailAddress="teresa0@adventure-works.com", Phone="129-555-0110" },
            new Customer() { ID=44, LastName="Ault", FirstName="John", EmailAddress="john7@adventure-works.com", Phone="1 (11) 500 555-0139" },
            new Customer() { ID=45, LastName="Avalos", FirstName="Robert", EmailAddress="robert2@adventure-works.com", Phone="665-555-0198" },
            new Customer() { ID=46, LastName="Ayers", FirstName="Stephen", EmailAddress="stephen1@adventure-works.com", Phone="818-555-0171" },
            new Customer() { ID=47, LastName="Bacalzo", FirstName="Phillip", EmailAddress="phillip0@adventure-works.com", Phone="1 (11) 500 555-0187" },
            new Customer() { ID=48, LastName="Blanco", FirstName="Daniel", EmailAddress="daniel0@adventure-works.com", Phone="221-555-0167" },
            new Customer() { ID=49, LastName="Booth", FirstName="Cory", EmailAddress="cory0@adventure-works.com", Phone="121-555-0157" },
            new Customer() { ID=50, LastName="Bailey", FirstName="James", EmailAddress="james3@adventure-works.com", Phone="234-555-0112" },
            new Customer() { ID=51, LastName="Baldwin", FirstName="Douglas", EmailAddress="douglas1@adventure-works.com", Phone="583-555-0130" },
            new Customer() { ID=52, LastName="Bales", FirstName="Jennifer", EmailAddress="jennifer0@adventure-works.com", Phone="790-555-0112" },
            new Customer() { ID=53, LastName="Baltazar", FirstName="Alberto", EmailAddress="alberto0@adventure-works.com", Phone="780-555-0114" },
            new Customer() { ID=54, LastName="Banack", FirstName="Wayne", EmailAddress="wayne0@adventure-works.com", Phone="640-555-0189" },
            new Customer() { ID=55, LastName="Banks", FirstName="Darrell", EmailAddress="darrell0@adventure-works.com", Phone="816-555-0118" },
            new Customer() { ID=56, LastName="Barbariol", FirstName="Angela", EmailAddress="angela1@adventure-works.com", Phone="134-555-0182" },
            new Customer() { ID=57, LastName="Barber", FirstName="David", EmailAddress="david9@adventure-works.com", Phone="752-555-0115" },
            new Customer() { ID=58, LastName="Barker", FirstName="Robert", EmailAddress="robert3@adventure-works.com", Phone="241-555-0112" },
            new Customer() { ID=59, LastName="Barley", FirstName="Rebecca", EmailAddress="rebecca1@adventure-works.com", Phone="1 (11) 500 555-0151" },
            new Customer() { ID=60, LastName="Barlow", FirstName="Brenda", EmailAddress="brenda1@adventure-works.com", Phone="1 (11) 500 555-0168" },
            new Customer() { ID=61, LastName="Barnhill", FirstName="Josh", EmailAddress="josh0@adventure-works.com", Phone="584-555-0192" },
            new Customer() { ID=62, LastName="Barr", FirstName="Adam", EmailAddress="adam0@adventure-works.com", Phone="726-555-0191" },
            new Customer() { ID=63, LastName="Barrera", FirstName="Norma", EmailAddress="norma0@adventure-works.com", Phone="1 (11) 500 555-0187" },
            new Customer() { ID=64, LastName="Barzdukas", FirstName="Gytis", EmailAddress="gytis0@adventure-works.com", Phone="257-555-0119" },
            new Customer() { ID=65, LastName="Bartness", FirstName="David", EmailAddress="david10@adventure-works.com", Phone="1 (11) 500 555-0112" },
            new Customer() { ID=66, LastName="Bates", FirstName="Karel", EmailAddress="karel0@adventure-works.com", Phone="916-555-0133" },
            new Customer() { ID=67, LastName="Bauer", FirstName="Ciro", EmailAddress="ciro0@adventure-works.com", Phone="115-555-0170" },
            new Customer() { ID=68, LastName="Beanston", FirstName="Glenna", EmailAddress="glenna0@adventure-works.com", Phone="1 (11) 500 555-0113" },
            new Customer() { ID=69, LastName="Beasley", FirstName="Shaun", EmailAddress="shaun0@adventure-works.com", Phone="396-555-0187" },
            new Customer() { ID=70, LastName="Beaver", FirstName="John", EmailAddress="john8@adventure-works.com", Phone="521-555-0195" },
            new Customer() { ID=71, LastName="Beck", FirstName="Christopher", EmailAddress="christopher1@adventure-works.com", Phone="1 (11) 500 555-0132" },
            new Customer() { ID=72, LastName="Beck", FirstName="Bradley", EmailAddress="bradley0@adventure-works.com", Phone="1 (11) 500 555-0127" },
            new Customer() { ID=73, LastName="Becker", FirstName="Benjamin", EmailAddress="benjamin1@adventure-works.com", Phone="1 (11) 500 555-0140" },
            new Customer() { ID=74, LastName="Beebe", FirstName="Ann", EmailAddress="ann0@adventure-works.com", Phone="277-555-0169" },
            new Customer() { ID=75, LastName="Belli", FirstName="Shane", EmailAddress="shane1@adventure-works.com", Phone="843-555-0175" },
            new Customer() { ID=76, LastName="Alan", FirstName="Stanley", EmailAddress="stanley0@adventure-works.com", Phone="156-555-0126" },
            new Customer() { ID=77, LastName="Bendixen", FirstName="Mason", EmailAddress="mason0@adventure-works.com", Phone="608-555-0114" },
            new Customer() { ID=78, LastName="Bennetts", FirstName="John", EmailAddress="john9@adventure-works.com", Phone="1 (11) 500 555-0163" },
            new Customer() { ID=79, LastName="Ben-Sachar", FirstName="Ido", EmailAddress="ido0@adventure-works.com", Phone="973-555-0112" },
            new Customer() { ID=80, LastName="Benson", FirstName="Edna", EmailAddress="edna0@adventure-works.com", Phone="789-555-0189" },
            new Customer() { ID=81, LastName="Benson", FirstName="Payton", EmailAddress="payton0@adventure-works.com", Phone="528-555-0183" },
            new Customer() { ID=82, LastName="Benson", FirstName="Max", EmailAddress="max0@adventure-works.com", Phone="599-555-0160" },
            new Customer() { ID=83, LastName="Bent", FirstName="Scot", EmailAddress="scot0@adventure-works.com", Phone="1 (11) 500 555-0177" },
            new Customer() { ID=84, LastName="Bentley", FirstName="Richard", EmailAddress="richard0@adventure-works.com", Phone="911-555-0153" },
            new Customer() { ID=85, LastName="Berch", FirstName="Marian", EmailAddress="marian0@adventure-works.com", Phone="640-555-0198" },
            new Customer() { ID=86, LastName="Berge", FirstName="Karen", EmailAddress="karen2@adventure-works.com", Phone="813-555-0173" },
            new Customer() { ID=87, LastName="Berger", FirstName="Alexander", EmailAddress="alexander0@adventure-works.com", Phone="519-555-0151" },
            new Customer() { ID=88, LastName="Berger", FirstName="John", EmailAddress="john10@adventure-works.com", Phone="156-555-0111" },
            new Customer() { ID=89, LastName="Bergin", FirstName="Kris", EmailAddress="kris0@adventure-works.com", Phone="144-555-0175" },
            new Customer() { ID=90, LastName="Berglund", FirstName="Andreas", EmailAddress="andreas1@adventure-works.com", Phone="795-555-0116" },
            new Customer() { ID=91, LastName="Bernacchi", FirstName="Robert", EmailAddress="robert4@adventure-works.com", Phone="449-555-0176" },
            new Customer() { ID=92, LastName="Berndt", FirstName="Matthias", EmailAddress="matthias1@adventure-works.com", Phone="384-555-0169" },
            new Customer() { ID=93, LastName="Berry", FirstName="John", EmailAddress="john11@adventure-works.com", Phone="471-555-0181" },
            new Customer() { ID=94, LastName="Brown", FirstName="Steven", EmailAddress="steven1@adventure-works.com", Phone="280-555-0124" },
            new Customer() { ID=95, LastName="Bidelman", FirstName="Chris", EmailAddress="chris4@adventure-works.com", Phone="609-555-0186" },
            new Customer() { ID=96, LastName="Billstrom", FirstName="Mary", EmailAddress="mary3@adventure-works.com", Phone="1 (11) 500 555-0136" },
            new Customer() { ID=97, LastName="Bischoff", FirstName="Jimmy", EmailAddress="jimmy1@adventure-works.com", Phone="992-555-0111" },
            new Customer() { ID=98, LastName="Bishop", FirstName="Mary", EmailAddress="mary4@adventure-works.com", Phone="176-555-0136" },
            new Customer() { ID=99, LastName="Black", FirstName="Mae", EmailAddress="mae1@adventure-works.com", Phone="264-555-0143" },
            new Customer() { ID=100, LastName="Blackwell", FirstName="Jackie", EmailAddress="jackie0@adventure-works.com", Phone="972-555-0163" },
            new Customer() { ID=101, LastName="Blanton", FirstName="Donald", EmailAddress="donald0@adventure-works.com", Phone="357-555-0161" },
            new Customer() { ID=102, LastName="Burnett", FirstName="Linda", EmailAddress="linda4@adventure-works.com", Phone="121-555-0121" },
            new Customer() { ID=103, LastName="Blythe", FirstName="Michael", EmailAddress="michael11@adventure-works.com", Phone="126-555-0172" },
            new Customer() { ID=104, LastName="Bockenkamp", FirstName="Gabriel", EmailAddress="gabriel0@adventure-works.com", Phone="763-555-0145" },
            new Customer() { ID=105, LastName="Bohling", FirstName="Michael", EmailAddress="michael12@adventure-works.com", Phone="838-555-0147" },
            new Customer() { ID=106, LastName="Bolender", FirstName="Corinna", EmailAddress="corinna0@adventure-works.com", Phone="332-555-0142" },
            new Customer() { ID=107, LastName="Bonifaz", FirstName="Luis", EmailAddress="luis0@adventure-works.com", Phone="688-555-0113" },
            new Customer() { ID=108, LastName="Boseman", FirstName="Randall", EmailAddress="randall0@adventure-works.com", Phone="383-555-0117" },
            new Customer() { ID=109, LastName="Bourne", FirstName="Stephanie", EmailAddress="stephanie1@adventure-works.com", Phone="1 (11) 500 555-0122" },
            new Customer() { ID=110, LastName="Bowen", FirstName="Eli", EmailAddress="eli0@adventure-works.com", Phone="371-555-0143" },
            new Customer() { ID=111, LastName="Bowman", FirstName="Lester", EmailAddress="lester0@adventure-works.com", Phone="844-555-0112" },
            new Customer() { ID=112, LastName="Bradley", FirstName="David", EmailAddress="david11@adventure-works.com", Phone="954-555-0145" },
            new Customer() { ID=113, LastName="Brandon", FirstName="Cornelius", EmailAddress="cornelius0@adventure-works.com", Phone="229-555-0114" },
            new Customer() { ID=114, LastName="Bready", FirstName="Richard", EmailAddress="richard1@adventure-works.com", Phone="340-555-0131" },
            new Customer() { ID=115, LastName="Breer", FirstName="Sara", EmailAddress="sara0@adventure-works.com", Phone="545-555-0183" },
            new Customer() { ID=116, LastName="Bremer", FirstName="Ted", EmailAddress="ted0@adventure-works.com", Phone="962-555-0166" },
            new Customer() { ID=117, LastName="Brewer", FirstName="Alan", EmailAddress="alan1@adventure-works.com", Phone="494-555-0134" },
            new Customer() { ID=118, LastName="Brian", FirstName="Walter", EmailAddress="walter0@adventure-works.com", Phone="163-555-0155" },
            new Customer() { ID=119, LastName="Bright", FirstName="Christopher", EmailAddress="christopher2@adventure-works.com", Phone="162-555-0166" },
            new Customer() { ID=120, LastName="Brink", FirstName="Carol", EmailAddress="carol1@adventure-works.com", Phone="513-555-0149" },
            new Customer() { ID=121, LastName="Brink", FirstName="David", EmailAddress="david12@adventure-works.com", Phone="1 (11) 500 555-0184" },
            new Customer() { ID=122, LastName="Brooks", FirstName="John", EmailAddress="john12@adventure-works.com", Phone="1 (11) 500 555-0179" },
            new Customer() { ID=123, LastName="Brooks", FirstName="Willie", EmailAddress="willie0@adventure-works.com", Phone="525-555-0174" },
            new Customer() { ID=124, LastName="Brown", FirstName="Carolee", EmailAddress="carolee0@adventure-works.com", Phone="1 (11) 500 555-0146" },
            new Customer() { ID=125, LastName="Brown", FirstName="Jo", EmailAddress="jo2@adventure-works.com", Phone="689-555-0130" },
            new Customer() { ID=126, LastName="Brown", FirstName="Robert", EmailAddress="robert5@adventure-works.com", Phone="575-555-0189" },
            new Customer() { ID=127, LastName="Browne", FirstName="Kevin", EmailAddress="kevin3@adventure-works.com", Phone="496-555-0150" },
            new Customer() { ID=128, LastName="Browning", FirstName="Mary", EmailAddress="mary5@adventure-works.com", Phone="658-555-0146" },
            new Customer() { ID=129, LastName="Browning", FirstName="Dave", EmailAddress="dave0@adventure-works.com", Phone="428-555-0162" },
            new Customer() { ID=130, LastName="Browqett", FirstName="Bridget", EmailAddress="bridget0@adventure-works.com", Phone="1 (11) 500 555-0122" },
            new Customer() { ID=131, LastName="Brumfield", FirstName="Eric", EmailAddress="eric3@adventure-works.com", Phone="644-555-0114" },
            new Customer() { ID=132, LastName="Brummer", FirstName="Dick", EmailAddress="dick0@adventure-works.com", Phone="581-555-0189" },
            new Customer() { ID=133, LastName="Brundage", FirstName="Michael", EmailAddress="michael13@adventure-works.com", Phone="128-555-0148" },
            new Customer() { ID=134, LastName="Bruner", FirstName="Shirley", EmailAddress="shirley0@adventure-works.com", Phone="383-555-0155" },
            new Customer() { ID=135, LastName="Brunner", FirstName="June", EmailAddress="june0@adventure-works.com", Phone="249-555-0172" },
            new Customer() { ID=136, LastName="Bruno", FirstName="Dirk", EmailAddress="dirk0@adventure-works.com", Phone="817-555-0114" },
            new Customer() { ID=137, LastName="Buchanan", FirstName="Nancy", EmailAddress="nancy1@adventure-works.com", Phone="1 (11) 500 555-0183" },
            new Customer() { ID=138, LastName="Bueno", FirstName="Janaina Barreiro Gambaro", EmailAddress="janainabarreirogambaro0@adventure-works.com", Phone="476-555-0184" },
            new Customer() { ID=139, LastName="Buensalido", FirstName="Edward", EmailAddress="edward0@adventure-works.com", Phone="315-555-0166" },
            new Customer() { ID=140, LastName="Burke", FirstName="Megan", EmailAddress="megan0@adventure-works.com", Phone="148-555-0149" },
            new Customer() { ID=141, LastName="Burkhardt", FirstName="Ingrid", EmailAddress="ingrid0@adventure-works.com", Phone="857-555-0187" },
            new Customer() { ID=142, LastName="Burkhardt", FirstName="Karren", EmailAddress="karren0@adventure-works.com", Phone="652-555-0132" },
            new Customer() { ID=143, LastName="Burlacu", FirstName="Ovidiu", EmailAddress="ovidiu1@adventure-works.com", Phone="710-555-0116" },
            new Customer() { ID=144, LastName="Burnell", FirstName="Dana", EmailAddress="dana0@adventure-works.com", Phone="1 (11) 500 555-0136" },
            new Customer() { ID=145, LastName="Burnett", FirstName="Timothy", EmailAddress="timothy0@adventure-works.com", Phone="251-555-0172" },
            new Customer() { ID=146, LastName="Burton", FirstName="Stephen", EmailAddress="stephen2@adventure-works.com", Phone="1 (11) 500 555-0129" },
            new Customer() { ID=147, LastName="Buskirk", FirstName="Deanna", EmailAddress="deanna0@adventure-works.com", Phone="131-555-0171" },
            new Customer() { ID=148, LastName="Bustamante", FirstName="Jared", EmailAddress="jared0@adventure-works.com", Phone="164-555-0147" },
            new Customer() { ID=149, LastName="Byham", FirstName="Richard", EmailAddress="richard2@adventure-works.com", Phone="1 (11) 500 555-0138" },
            new Customer() { ID=150, LastName="Byrnes", FirstName="David", EmailAddress="david13@adventure-works.com", Phone="1 (11) 500 555-0199" },
            new Customer() { ID=151, LastName="Calafato", FirstName="Ryan", EmailAddress="ryan1@adventure-works.com", Phone="726-555-0155" },
            new Customer() { ID=152, LastName="Caldwell", FirstName="Sylvia", EmailAddress="sylvia0@adventure-works.com", Phone="1 (11) 500 555-0122" },
            new Customer() { ID=153, LastName="Caldwell", FirstName="Mari", EmailAddress="mari0@adventure-works.com", Phone="1 (11) 500 555-0118" },
            new Customer() { ID=154, LastName="Calone", FirstName="Barbara", EmailAddress="barbara2@adventure-works.com", Phone="145-555-0152" },
            new Customer() { ID=155, LastName="Camacho", FirstName="Lindsey", EmailAddress="lindsey0@adventure-works.com", Phone="827-555-0143" },
            new Customer() { ID=156, LastName="Camargo", FirstName="Gustavo", EmailAddress="gustavo1@adventure-works.com", Phone="1 (11) 500 555-0118" },
            new Customer() { ID=157, LastName="Cameron", FirstName="DeeDee", EmailAddress="deedee0@adventure-works.com", Phone="377-555-0158" },
            new Customer() { ID=158, LastName="Lee", FirstName="Deborah", EmailAddress="deborah1@adventure-works.com", Phone="1 (11) 500 555-0190" },
            new Customer() { ID=159, LastName="Campbell", FirstName="Joan", EmailAddress="joan0@adventure-works.com", Phone="700-555-0155" },
            new Customer() { ID=160, LastName="Campbell", FirstName="David", EmailAddress="david14@adventure-works.com", Phone="756-555-0117" },
            new Customer() { ID=161, LastName="Campen", FirstName="Henry", EmailAddress="henry0@adventure-works.com", Phone="635-555-0126" },
            new Customer() { ID=162, LastName="Cannon", FirstName="Chris", EmailAddress="chris5@adventure-works.com", Phone="118-555-0131" },
            new Customer() { ID=163, LastName="Cantoni", FirstName="Joseph", EmailAddress="joseph0@adventure-works.com", Phone="965-555-0112" },
            new Customer() { ID=164, LastName="Canuto", FirstName="Suzana De Abreu", EmailAddress="suzanadeabreu0@adventure-works.com", Phone="990-555-0141" },
            new Customer() { ID=165, LastName="Cao", FirstName="Jun", EmailAddress="jun1@adventure-works.com", Phone="488-555-0130" },
            new Customer() { ID=166, LastName="Caprio", FirstName="Johnny", EmailAddress="johnny0@adventure-works.com", Phone="112-555-0191" },
            new Customer() { ID=167, LastName="Carey", FirstName="Richard", EmailAddress="richard3@adventure-works.com", Phone="1 (11) 500 555-0140" },
            new Customer() { ID=168, LastName="Carlisle", FirstName="Carlton", EmailAddress="carlton0@adventure-works.com", Phone="193-555-0116" },
            new Customer() { ID=169, LastName="Carlson", FirstName="Ty Loren", EmailAddress="tyloren0@adventure-works.com", Phone="1 (11) 500 555-0120" },
            new Customer() { ID=170, LastName="Carmichael", FirstName="Jane", EmailAddress="jane0@adventure-works.com", Phone="716-555-0167" },
            new Customer() { ID=171, LastName="Carmody", FirstName="Jovita", EmailAddress="jovita0@adventure-works.com", Phone="646-555-0137" },
            new Customer() { ID=172, LastName="Carnes", FirstName="Steve", EmailAddress="steve1@adventure-works.com", Phone="268-555-0184" },
            new Customer() { ID=173, LastName="Caro", FirstName="Fernando", EmailAddress="fernando0@adventure-works.com", Phone="1 (11) 500 555-0163" },
            new Customer() { ID=174, LastName="Caron", FirstName="Rob", EmailAddress="rob2@adventure-works.com", Phone="620-555-0117" },
            new Customer() { ID=175, LastName="Carothers", FirstName="Andy", EmailAddress="andy1@adventure-works.com", Phone="944-555-0148" },
            new Customer() { ID=176, LastName="Carreras", FirstName="Donna", EmailAddress="donna0@adventure-works.com", Phone="279-555-0130" },
            new Customer() { ID=177, LastName="Carroll", FirstName="Rosmarie", EmailAddress="rosmarie0@adventure-works.com", Phone="244-555-0112" },
            new Customer() { ID=178, LastName="Carroll", FirstName="Matthew", EmailAddress="matthew0@adventure-works.com", Phone="1 (11) 500 555-0191" },
            new Customer() { ID=179, LastName="Castellucio", FirstName="Joseph", EmailAddress="joseph1@adventure-works.com", Phone="180-555-0114" },
            new Customer() { ID=180, LastName="Carlson", FirstName="Pamela", EmailAddress="pamela1@adventure-works.com", Phone="353-555-0188" },
            new Customer() { ID=181, LastName="Casts", FirstName="Raul", EmailAddress="raul0@adventure-works.com", Phone="362-555-0162" },
            new Customer() { ID=182, LastName="Catalano", FirstName="Elizabeth", EmailAddress="elizabeth1@adventure-works.com", Phone="242-555-0181" },
            new Customer() { ID=183, LastName="Cavallari", FirstName="Matthew", EmailAddress="matthew1@adventure-works.com", Phone="695-555-0161" },
            new Customer() { ID=184, LastName="Cavendish", FirstName="Brigid", EmailAddress="brigid0@adventure-works.com", Phone="1 (11) 500 555-0178" },
            new Customer() { ID=185, LastName="Cencini", FirstName="Andrew", EmailAddress="andrew2@adventure-works.com", Phone="644-555-0111" },
            new Customer() { ID=186, LastName="Cereghino", FirstName="Stacey", EmailAddress="stacey0@adventure-works.com", Phone="351-555-0131" },
            new Customer() { ID=187, LastName="Cetinok", FirstName="Baris", EmailAddress="baris1@adventure-works.com", Phone="301-555-0128" },
            new Customer() { ID=188, LastName="Chai", FirstName="Sean", EmailAddress="sean3@adventure-works.com", Phone="1 (11) 500 555-0134" },
            new Customer() { ID=189, LastName="Chambers", FirstName="Pat", EmailAddress="pat1@adventure-works.com", Phone="127-555-0124" },
            new Customer() { ID=190, LastName="Chandler", FirstName="Forrest", EmailAddress="forrest0@adventure-works.com", Phone="448-555-0179" },
            new Customer() { ID=191, LastName="Chapla", FirstName="Lee", EmailAddress="lee0@adventure-works.com", Phone="223-555-0184" },
            new Customer() { ID=192, LastName="Chapman", FirstName="Greg", EmailAddress="greg1@adventure-works.com", Phone="708-555-0169" },
            new Customer() { ID=193, LastName="Charney", FirstName="Neil", EmailAddress="neil0@adventure-works.com", Phone="1 (11) 500 555-0180" },
            new Customer() { ID=194, LastName="Chen", FirstName="Hao", EmailAddress="hao1@adventure-works.com", Phone="117-555-0173" },
            new Customer() { ID=195, LastName="Chen", FirstName="John", EmailAddress="john13@adventure-works.com", Phone="514-555-0128" },
            new Customer() { ID=196, LastName="Chow", FirstName="Pei", EmailAddress="pei0@adventure-works.com", Phone="789-555-0184" },
            new Customer() { ID=197, LastName="Cheng", FirstName="Yao-Qiang", EmailAddress="yao-qiang0@adventure-works.com", Phone="344-555-0181" },
            new Customer() { ID=198, LastName="Chesnut", FirstName="Nicky", EmailAddress="nicky0@adventure-works.com", Phone="264-555-0164" },
            new Customer() { ID=199, LastName="Chestnut", FirstName="Susan", EmailAddress="susan2@adventure-works.com", Phone="1 (11) 500 555-0181" },
            new Customer() { ID=200, LastName="Chisholm", FirstName="Martin", EmailAddress="martin0@adventure-works.com", Phone="1 (11) 500 555-0142" },
            new Customer() { ID=201, LastName="Choi", FirstName="Mike", EmailAddress="mike1@adventure-works.com", Phone="727-555-0190" },
            new Customer() { ID=202, LastName="Choin", FirstName="Ruth", EmailAddress="ruth1@adventure-works.com", Phone="273-555-0181" },
            new Customer() { ID=203, LastName="Chor", FirstName="Anthony", EmailAddress="anthony0@adventure-works.com", Phone="429-555-0145" },
            new Customer() { ID=204, LastName="Christensen", FirstName="Charles", EmailAddress="charles1@adventure-works.com", Phone="334-555-0146" },
            new Customer() { ID=205, LastName="Christie", FirstName="Jill", EmailAddress="jill1@adventure-works.com", Phone="927-555-0198" },
            new Customer() { ID=206, LastName="Clark", FirstName="Alice", EmailAddress="alice1@adventure-works.com", Phone="221-555-0141" },
            new Customer() { ID=207, LastName="Clark", FirstName="Gina", EmailAddress="gina0@adventure-works.com", Phone="539-555-0142" },
            new Customer() { ID=208, LastName="Clark", FirstName="James", EmailAddress="james4@adventure-works.com", Phone="1 (11) 500 555-0176" },
            new Customer() { ID=209, LastName="Clayton", FirstName="Jane", EmailAddress="jane1@adventure-works.com", Phone="206-555-0195" },
            new Customer() { ID=210, LastName="Cleary", FirstName="Kristine", EmailAddress="kristine0@adventure-works.com", Phone="250-555-0127" },
            new Customer() { ID=211, LastName="Cobb", FirstName="Teanna", EmailAddress="teanna0@adventure-works.com", Phone="661-555-0168" },
            new Customer() { ID=212, LastName="Coffman", FirstName="Connie", EmailAddress="connie0@adventure-works.com", Phone="426-555-0181" },
            new Customer() { ID=213, LastName="Cole", FirstName="Jeanette", EmailAddress="jeanette0@adventure-works.com", Phone="159-555-0190" },
            new Customer() { ID=214, LastName="Coleman", FirstName="Eric", EmailAddress="eric4@adventure-works.com", Phone="1 (11) 500 555-0140" },
            new Customer() { ID=215, LastName="Coleman", FirstName="Pat", EmailAddress="pat2@adventure-works.com", Phone="292-555-0128" },
            new Customer() { ID=216, LastName="Collins", FirstName="Takiko", EmailAddress="takiko0@adventure-works.com", Phone="987-555-0126" },
            new Customer() { ID=217, LastName="Colon", FirstName="John", EmailAddress="john14@adventure-works.com", Phone="397-555-0144" },
            new Customer() { ID=218, LastName="Colvin", FirstName="Scott", EmailAddress="scott1@adventure-works.com", Phone="119-555-0144" },
            new Customer() { ID=219, LastName="Con", FirstName="Aaron", EmailAddress="aaron0@adventure-works.com", Phone="652-555-0115" },
            new Customer() { ID=220, LastName="Connelly", FirstName="Peter", EmailAddress="peter2@adventure-works.com", Phone="1 (11) 500 555-0117" },
            new Customer() { ID=221, LastName="Conner", FirstName="William", EmailAddress="william1@adventure-works.com", Phone="383-555-0111" },
            new Customer() { ID=222, LastName="Conroy", FirstName="Stephanie", EmailAddress="stephanie2@adventure-works.com", Phone="752-555-0187" },
            new Customer() { ID=223, LastName="Consentino", FirstName="Amy", EmailAddress="amy2@adventure-works.com", Phone="1 (11) 500 555-0133" },
            new Customer() { ID=224, LastName="Contreras", FirstName="Dorothy", EmailAddress="dorothy0@adventure-works.com", Phone="428-555-0176" },
            new Customer() { ID=225, LastName="Cook", FirstName="Patrick", EmailAddress="patrick2@adventure-works.com", Phone="884-555-0193" },
            new Customer() { ID=226, LastName="Cooper", FirstName="Scott", EmailAddress="scott2@adventure-works.com", Phone="773-555-0182" },
            new Customer() { ID=227, LastName="Corets", FirstName="Eva", EmailAddress="eva0@adventure-works.com", Phone="542-555-0164" },
            new Customer() { ID=228, LastName="Coriell", FirstName="Marlin", EmailAddress="marlin0@adventure-works.com", Phone="941-555-0155" },
            new Customer() { ID=229, LastName="Cornelsen", FirstName="Ryan", EmailAddress="ryan2@adventure-works.com", Phone="1 (11) 500 555-0147" },
            new Customer() { ID=230, LastName="Costa Da Silva", FirstName="Bruno", EmailAddress="bruno0@adventure-works.com", Phone="140-555-0143" },
            new Customer() { ID=231, LastName="Cox", FirstName="Pamela", EmailAddress="pamela2@adventure-works.com", Phone="945-555-0112" },
            new Customer() { ID=232, LastName="Creasey", FirstName="Jack", EmailAddress="jack2@adventure-works.com", Phone="539-555-0182" },
            new Customer() { ID=233, LastName="Crow", FirstName="Sharon", EmailAddress="sharon1@adventure-works.com", Phone="889-555-0176" },
            new Customer() { ID=234, LastName="Crow", FirstName="Shelley", EmailAddress="shelley1@adventure-works.com", Phone="1 (11) 500 555-0148" },
            new Customer() { ID=235, LastName="Culbertson", FirstName="Grant", EmailAddress="grant1@adventure-works.com", Phone="859-555-0173" },
            new Customer() { ID=236, LastName="Culp", FirstName="Scott", EmailAddress="scott3@adventure-works.com", Phone="119-555-0167" },
            new Customer() { ID=237, LastName="Cunningham", FirstName="Conor", EmailAddress="conor0@adventure-works.com", Phone="115-555-0113" },
            new Customer() { ID=238, LastName="Curry", FirstName="Jose", EmailAddress="jose2@adventure-works.com", Phone="937-555-0136" },
            new Customer() { ID=239, LastName="D'Hers", FirstName="Thierry", EmailAddress="thierry1@adventure-works.com", Phone="680-555-0192" },
            new Customer() { ID=240, LastName="Danner", FirstName="Ryan", EmailAddress="ryan3@adventure-works.com", Phone="1 (11) 500 555-0178" },
            new Customer() { ID=241, LastName="Danseglio", FirstName="Mike", EmailAddress="mike2@adventure-works.com", Phone="219-555-0126" },
            new Customer() { ID=242, LastName="Davis", FirstName="Megan", EmailAddress="megan1@adventure-works.com", Phone="839-555-0198" },
            new Customer() { ID=243, LastName="De Matos Miranda Filho", FirstName="Alvaro", EmailAddress="alvaro0@adventure-works.com", Phone="551-555-0155" },
            new Customer() { ID=244, LastName="De Oliveira", FirstName="Jose", EmailAddress="jose3@adventure-works.com", Phone="188-555-0152" },
            new Customer() { ID=245, LastName="Dean", FirstName="Jacob", EmailAddress="jacob0@adventure-works.com", Phone="767-555-0151" },
            new Customer() { ID=246, LastName="Deborde", FirstName="Alexander", EmailAddress="alexander1@adventure-works.com", Phone="394-555-0176" },
            new Customer() { ID=247, LastName="Decker", FirstName="Barbara", EmailAddress="barbara3@adventure-works.com", Phone="1 (11) 500 555-0113" },
            new Customer() { ID=248, LastName="DeGrasse", FirstName="Kirk", EmailAddress="kirk1@adventure-works.com", Phone="820-555-0166" },
            new Customer() { ID=249, LastName="Delaney", FirstName="Aidan", EmailAddress="aidan0@adventure-works.com", Phone="358-555-0188" },
            new Customer() { ID=250, LastName="Delmarco", FirstName="Stefan", EmailAddress="stefan0@adventure-works.com", Phone="819-555-0186" },
            new Customer() { ID=251, LastName="Demicell", FirstName="Shawn", EmailAddress="shawn0@adventure-works.com", Phone="175-555-0198" },
            new Customer() { ID=252, LastName="Demott Jr", FirstName="Della", EmailAddress="della0@adventure-works.com", Phone="752-555-0185" },
            new Customer() { ID=253, LastName="Deniut", FirstName="Bruno", EmailAddress="bruno1@adventure-works.com", Phone="1 (11) 500 555-0118" },
            new Customer() { ID=254, LastName="Dennis", FirstName="Helen", EmailAddress="helen0@adventure-works.com", Phone="572-555-0156" },
            new Customer() { ID=255, LastName="Desai", FirstName="Prashanth", EmailAddress="prashanth0@adventure-works.com", Phone="138-555-0156" },
            new Customer() { ID=256, LastName="Desalvo", FirstName="Bev", EmailAddress="bev0@adventure-works.com", Phone="143-555-0113" },
            new Customer() { ID=257, LastName="Diaz", FirstName="Brenda", EmailAddress="brenda2@adventure-works.com", Phone="147-555-0192" },
            new Customer() { ID=258, LastName="Dickmann", FirstName="Gabriele", EmailAddress="gabriele0@adventure-works.com", Phone="835-555-0116" },
            new Customer() { ID=259, LastName="Dickson", FirstName="Holly", EmailAddress="holly0@adventure-works.com", Phone="1 (11) 500 555-0197" },
            new Customer() { ID=260, LastName="Dievendorff", FirstName="Dick", EmailAddress="dick1@adventure-works.com", Phone="1 (11) 500 555-0193" },
            new Customer() { ID=261, LastName="Dillon", FirstName="Rudolph", EmailAddress="rudolph0@adventure-works.com", Phone="722-555-0169" },
            new Customer() { ID=262, LastName="Dixon", FirstName="Andrew", EmailAddress="andrew3@adventure-works.com", Phone="576-555-0171" },
            new Customer() { ID=263, LastName="Dockter", FirstName="Blaine", EmailAddress="blaine0@adventure-works.com", Phone="156-555-0187" },
            new Customer() { ID=264, LastName="Dodd", FirstName="Cindy", EmailAddress="cindy0@adventure-works.com", Phone="706-555-0140" },
            new Customer() { ID=265, LastName="Donovan", FirstName="John", EmailAddress="john15@adventure-works.com", Phone="754-555-0134" },
            new Customer() { ID=266, LastName="Doyle", FirstName="Patricia", EmailAddress="patricia0@adventure-works.com", Phone="899-555-0134" },
            new Customer() { ID=267, LastName="Drury", FirstName="Gerald", EmailAddress="gerald0@adventure-works.com", Phone="169-555-0178" },
            new Customer() { ID=268, LastName="Drury", FirstName="Gary", EmailAddress="gary2@adventure-works.com", Phone="698-555-0183" },
            new Customer() { ID=269, LastName="D'sa", FirstName="Reuben", EmailAddress="reuben1@adventure-works.com", Phone="916-555-0137" },
            new Customer() { ID=270, LastName="Dudenhoefer", FirstName="Ed", EmailAddress="ed1@adventure-works.com", Phone="1 (11) 500 555-0153" },
            new Customer() { ID=271, LastName="Duerr", FirstName="Bernard", EmailAddress="bernard0@adventure-works.com", Phone="158-555-0188" },
            new Customer() { ID=272, LastName="Duff", FirstName="Tish", EmailAddress="tish0@adventure-works.com", Phone="1 (11) 500 555-0178" },
            new Customer() { ID=273, LastName="Dumitrascu", FirstName="Adrian", EmailAddress="adrian0@adventure-works.com", Phone="362-555-0121" },
            new Customer() { ID=274, LastName="Duncan", FirstName="Bart", EmailAddress="bart0@adventure-works.com", Phone="539-555-0121" },
            new Customer() { ID=275, LastName="Dusza", FirstName="Maciej", EmailAddress="maciej1@adventure-works.com", Phone="962-555-0144" },
            new Customer() { ID=276, LastName="Dyck", FirstName="Shelley", EmailAddress="shelley2@adventure-works.com", Phone="716-555-0123" },
            new Customer() { ID=277, LastName="Ecoffey", FirstName="Linda", EmailAddress="linda5@adventure-works.com", Phone="674-555-0188" },
            new Customer() { ID=278, LastName="Eldridge", FirstName="Carla", EmailAddress="carla1@adventure-works.com", Phone="186-555-0135" },
            new Customer() { ID=279, LastName="Elliott", FirstName="Carol", EmailAddress="carol2@adventure-works.com", Phone="847-555-0151" },
            new Customer() { ID=280, LastName="Elliott", FirstName="Shannon", EmailAddress="shannon0@adventure-works.com", Phone="425-555-0158" },
            new Customer() { ID=281, LastName="Elson", FirstName="Jauna", EmailAddress="jauna0@adventure-works.com", Phone="185-555-0190" },
            new Customer() { ID=282, LastName="Emanuel", FirstName="Michael", EmailAddress="michael14@adventure-works.com", Phone="1 (11) 500 555-0130" },
            new Customer() { ID=283, LastName="Eminhizer", FirstName="Terry", EmailAddress="terry1@adventure-works.com", Phone="1 (11) 500 555-0176" },
            new Customer() { ID=284, LastName="Emory", FirstName="John", EmailAddress="john16@adventure-works.com", Phone="691-555-0149" },
            new Customer() { ID=285, LastName="Erickson", FirstName="Gail", EmailAddress="gail1@adventure-works.com", Phone="834-555-0132" },
            new Customer() { ID=286, LastName="Erickson", FirstName="Mark", EmailAddress="mark2@adventure-works.com", Phone="962-555-0112" },
            new Customer() { ID=287, LastName="Espinoza", FirstName="Martha", EmailAddress="martha0@adventure-works.com", Phone="753-555-0179" },
            new Customer() { ID=288, LastName="Estes", FirstName="Julie", EmailAddress="julie0@adventure-works.com", Phone="1 (11) 500 555-0123" },
            new Customer() { ID=289, LastName="Esteves", FirstName="Janeth", EmailAddress="janeth1@adventure-works.com", Phone="1 (11) 500 555-0136" },
            new Customer() { ID=290, LastName="Evans", FirstName="Twanna", EmailAddress="twanna0@adventure-works.com", Phone="554-555-0124" },
            new Customer() { ID=291, LastName="Evans", FirstName="Ann", EmailAddress="ann1@adventure-works.com", Phone="252-555-0127" },
            new Customer() { ID=292, LastName="Evans", FirstName="John", EmailAddress="john17@adventure-works.com", Phone="581-555-0172" },
            new Customer() { ID=293, LastName="Faeber", FirstName="Marc", EmailAddress="marc1@adventure-works.com", Phone="1 (11) 500 555-0191" },
            new Customer() { ID=294, LastName="Fakhouri", FirstName="Fadi", EmailAddress="fadi1@adventure-works.com", Phone="153-555-0114" },
            new Customer() { ID=295, LastName="Farino", FirstName="Carolyn", EmailAddress="carolyn0@adventure-works.com", Phone="957-555-0125" },
            new Customer() { ID=296, LastName="Farrell", FirstName="Geri", EmailAddress="geri0@adventure-works.com", Phone="329-555-0183" },
            new Customer() { ID=297, LastName="Feng", FirstName="Hanying", EmailAddress="hanying1@adventure-works.com", Phone="475-555-0188" },
            new Customer() { ID=298, LastName="Finley", FirstName="Rhoda", EmailAddress="rhoda0@adventure-works.com", Phone="920-555-0191" },
            new Customer() { ID=299, LastName="Fitzgerald", FirstName="Duane", EmailAddress="duane0@adventure-works.com", Phone="1 (11) 500 555-0115" },
            new Customer() { ID=300, LastName="Fine", FirstName="James", EmailAddress="james5@adventure-works.com", Phone="993-555-0162" },
            new Customer() { ID=301, LastName="Flood", FirstName="Kathie", EmailAddress="kathie1@adventure-works.com", Phone="627-555-0192" },
            new Customer() { ID=302, LastName="Fluegel", FirstName="Jay", EmailAddress="jay2@adventure-works.com", Phone="1 (11) 500 555-0119" },
            new Customer() { ID=303, LastName="Focht", FirstName="Kelly", EmailAddress="kelly0@adventure-works.com", Phone="272-555-0123" },
            new Customer() { ID=304, LastName="Ford", FirstName="Jeffrey", EmailAddress="jeffrey1@adventure-works.com", Phone="395-555-0128" },
            new Customer() { ID=305, LastName="Fort", FirstName="Garth", EmailAddress="garth0@adventure-works.com", Phone="768-555-0125" },
            new Customer() { ID=306, LastName="Fox", FirstName="Dorothy", EmailAddress="dorothy1@adventure-works.com", Phone="191-555-0198" },
            new Customer() { ID=307, LastName="Frazier", FirstName="Judith", EmailAddress="judith0@adventure-works.com", Phone="721-555-0163" },
            new Customer() { ID=308, LastName="Fredericksen", FirstName="John", EmailAddress="john18@adventure-works.com", Phone="1 (11) 500 555-0123" },
            new Customer() { ID=309, LastName="French", FirstName="Susan", EmailAddress="susan3@adventure-works.com", Phone="994-555-0194" },
            new Customer() { ID=310, LastName="Friedland", FirstName="Liam", EmailAddress="liam0@adventure-works.com", Phone="991-555-0148" },
            new Customer() { ID=311, LastName="Frintu", FirstName="Mihail", EmailAddress="mihail1@adventure-works.com", Phone="777-555-0163" },
            new Customer() { ID=312, LastName="Ford", FirstName="John", EmailAddress="john19@adventure-works.com", Phone="596-555-0153" },
            new Customer() { ID=313, LastName="Fulton", FirstName="Paul", EmailAddress="paul3@adventure-works.com", Phone="492-555-0146" },
            new Customer() { ID=314, LastName="Funk", FirstName="Don", EmailAddress="don1@adventure-works.com", Phone="1 (11) 500 555-0137" },
            new Customer() { ID=315, LastName="Gage", FirstName="Bob", EmailAddress="bob1@adventure-works.com", Phone="962-555-0175" },
            new Customer() { ID=316, LastName="Gallagher", FirstName="Aldeen", EmailAddress="aldeen0@adventure-works.com", Phone="653-555-0170" },
            new Customer() { ID=317, LastName="Galos", FirstName="Michael", EmailAddress="michael15@adventure-works.com", Phone="912-555-0149" },
            new Customer() { ID=318, LastName="Ganio", FirstName="Jon", EmailAddress="jon0@adventure-works.com", Phone="672-555-0112" },
            new Customer() { ID=319, LastName="Garza", FirstName="Kathleen", EmailAddress="kathleen0@adventure-works.com", Phone="150-555-0127" },
            new Customer() { ID=320, LastName="Gash", FirstName="Dominic", EmailAddress="dominic0@adventure-works.com", Phone="192-555-0173" },
            new Customer() { ID=321, LastName="Gates", FirstName="Janet", EmailAddress="janet1@adventure-works.com", Phone="710-555-0173" },
            new Customer() { ID=322, LastName="Gee", FirstName="Orlando", EmailAddress="orlando0@adventure-works.com", Phone="245-555-0173" },
            new Customer() { ID=323, LastName="Gehring", FirstName="Darren", EmailAddress="darren0@adventure-works.com", Phone="417-555-0182" },
            new Customer() { ID=324, LastName="Geist", FirstName="Jim", EmailAddress="jim1@adventure-works.com", Phone="724-555-0161" },
            new Customer() { ID=325, LastName="German", FirstName="Barbara", EmailAddress="barbara4@adventure-works.com", Phone="1 (11) 500 555-0181" },
            new Customer() { ID=326, LastName="Getzinger", FirstName="Tom", EmailAddress="tom2@adventure-works.com", Phone="1 (11) 500 555-0198" },
            new Customer() { ID=327, LastName="Giakoumakis", FirstName="Leo", EmailAddress="leo0@adventure-works.com", Phone="1 (11) 500 555-0169" },
            new Customer() { ID=328, LastName="Gibbens", FirstName="Cornett", EmailAddress="cornett0@adventure-works.com", Phone="1 (11) 500 555-0112" },
            new Customer() { ID=329, LastName="Giglio", FirstName="Frances", EmailAddress="frances1@adventure-works.com", Phone="692-555-0136" },
            new Customer() { ID=330, LastName="Gilbert", FirstName="Guy", EmailAddress="guy0@adventure-works.com", Phone="583-555-0198" },
            new Customer() { ID=331, LastName="Gilliat", FirstName="Janet", EmailAddress="janet2@adventure-works.com", Phone="521-555-0183" },
            new Customer() { ID=332, LastName="Gimmi", FirstName="Mary", EmailAddress="mary6@adventure-works.com", Phone="149-555-0196" },
            new Customer() { ID=333, LastName="Givens", FirstName="David", EmailAddress="david15@adventure-works.com", Phone="605-555-0111" },
            new Customer() { ID=334, LastName="Glenn", FirstName="Jeanie", EmailAddress="jeanie0@adventure-works.com", Phone="669-555-0149" },
            new Customer() { ID=335, LastName="Glimp", FirstName="Diane", EmailAddress="diane3@adventure-works.com", Phone="898-555-0137" },
            new Customer() { ID=336, LastName="Glynn", FirstName="James", EmailAddress="james6@adventure-works.com", Phone="1 (11) 500 555-0191" },
            new Customer() { ID=337, LastName="Gode", FirstName="Scott", EmailAddress="scott4@adventure-works.com", Phone="164-555-0145" },
            new Customer() { ID=338, LastName="Goktepe", FirstName="Mete", EmailAddress="mete0@adventure-works.com", Phone="637-555-0120" },
            new Customer() { ID=339, LastName="Goldberg", FirstName="Jossef", EmailAddress="jossef1@adventure-works.com", Phone="621-555-0157" },
            new Customer() { ID=340, LastName="Goldstein", FirstName="Brian", EmailAddress="brian4@adventure-works.com", Phone="495-555-0161" },
            new Customer() { ID=341, LastName="Gonzales", FirstName="Lynn", EmailAddress="lynn1@adventure-works.com", Phone="1 (11) 500 555-0180" },
            new Customer() { ID=342, LastName="Gonzales", FirstName="Linda", EmailAddress="linda6@adventure-works.com", Phone="433-555-0162" },
            new Customer() { ID=343, LastName="Gonzalez", FirstName="Abigail", EmailAddress="abigail0@adventure-works.com", Phone="121-555-0139" },
            new Customer() { ID=344, LastName="Graff", FirstName="Michael", EmailAddress="michael16@adventure-works.com", Phone="132-555-0150" },
            new Customer() { ID=345, LastName="Graham", FirstName="Derek", EmailAddress="derek0@adventure-works.com", Phone="674-555-0187" },
            new Customer() { ID=346, LastName="Graham", FirstName="Lowell", EmailAddress="lowell0@adventure-works.com", Phone="1 (11) 500 555-0168" },
            new Customer() { ID=347, LastName="Grande", FirstName="Jon", EmailAddress="jon1@adventure-works.com", Phone="1 (11) 500 555-0114" },
            new Customer() { ID=348, LastName="Greer", FirstName="Jane", EmailAddress="jane2@adventure-works.com", Phone="737-555-0163" },
            new Customer() { ID=349, LastName="Grisso", FirstName="Geoff", EmailAddress="geoff0@adventure-works.com", Phone="351-555-0130" },
            new Customer() { ID=350, LastName="Groncki", FirstName="Douglas", EmailAddress="douglas2@adventure-works.com", Phone="385-555-0140" },
            new Customer() { ID=351, LastName="Groth", FirstName="Brian", EmailAddress="brian5@adventure-works.com", Phone="461-555-0118" },
            new Customer() { ID=352, LastName="Gustafson", FirstName="Faith", EmailAddress="faith0@adventure-works.com", Phone="479-555-0129" },
            new Customer() { ID=353, LastName="Harrison", FirstName="Greg", EmailAddress="greg2@adventure-works.com", Phone="1 (11) 500 555-0112" },
            new Customer() { ID=354, LastName="Haemon", FirstName="Hattie", EmailAddress="hattie0@adventure-works.com", Phone="141-555-0172" },
            new Customer() { ID=355, LastName="Hagemann", FirstName="Matthew", EmailAddress="matthew2@adventure-works.com", Phone="552-555-0141" },
            new Customer() { ID=356, LastName="Hagens", FirstName="Erin", EmailAddress="erin1@adventure-works.com", Phone="244-555-0127" },
            new Customer() { ID=357, LastName="Haines", FirstName="Betty", EmailAddress="betty0@adventure-works.com", Phone="867-555-0114" },
            new Customer() { ID=358, LastName="Hall", FirstName="Karen", EmailAddress="karen3@adventure-works.com", Phone="623-555-0153" },
            new Customer() { ID=359, LastName="Hall", FirstName="Don", EmailAddress="don2@adventure-works.com", Phone="1 (11) 500 555-0182" },
            new Customer() { ID=360, LastName="Hamilton", FirstName="Bryan", EmailAddress="bryan2@adventure-works.com", Phone="344-555-0144" },
            new Customer() { ID=361, LastName="Hamilton", FirstName="James", EmailAddress="james7@adventure-works.com", Phone="418-555-0115" },
            new Customer() { ID=362, LastName="Hanif", FirstName="Kerim", EmailAddress="kerim0@adventure-works.com", Phone="216-555-0122" },
            new Customer() { ID=363, LastName="Handley", FirstName="Jean", EmailAddress="jean1@adventure-works.com", Phone="582-555-0113" },
            new Customer() { ID=364, LastName="Hanson", FirstName="Mark", EmailAddress="mark3@adventure-works.com", Phone="497-555-0147" },
            new Customer() { ID=365, LastName="Hapke", FirstName="William", EmailAddress="william2@adventure-works.com", Phone="1 (11) 500 555-0167" },
            new Customer() { ID=366, LastName="Harding", FirstName="Katherine", EmailAddress="katherine0@adventure-works.com", Phone="926-555-0159" },
            new Customer() { ID=367, LastName="Harrington", FirstName="Kimberly", EmailAddress="kimberly1@adventure-works.com", Phone="872-555-0171" },
            new Customer() { ID=368, LastName="Harrington", FirstName="Lucy", EmailAddress="lucy0@adventure-works.com", Phone="828-555-0186" },
            new Customer() { ID=369, LastName="Harris", FirstName="Keith", EmailAddress="keith0@adventure-works.com", Phone="170-555-0127" },
            new Customer() { ID=370, LastName="Hartwig", FirstName="Doris", EmailAddress="doris1@adventure-works.com", Phone="703-555-0158" },
            new Customer() { ID=371, LastName="Harui", FirstName="Roger", EmailAddress="roger0@adventure-works.com", Phone="774-555-0133" },
            new Customer() { ID=372, LastName="Hass", FirstName="Ann", EmailAddress="ann2@adventure-works.com", Phone="713-555-0168" },
            new Customer() { ID=373, LastName="Hassall", FirstName="Mark", EmailAddress="mark4@adventure-works.com", Phone="751-555-0119" },
            new Customer() { ID=374, LastName="Hasty", FirstName="Neal", EmailAddress="neal0@adventure-works.com", Phone="1 (11) 500 555-0191" },
            new Customer() { ID=375, LastName="Haugh", FirstName="James", EmailAddress="james8@adventure-works.com", Phone="763-555-0120" },
            new Customer() { ID=376, LastName="Hay", FirstName="Jeff", EmailAddress="jeff1@adventure-works.com", Phone="1 (11) 500 555-0182" },
            new Customer() { ID=377, LastName="Heaney", FirstName="Brenda", EmailAddress="brenda3@adventure-works.com", Phone="393-555-0167" },
            new Customer() { ID=378, LastName="Hendergart", FirstName="James", EmailAddress="james9@adventure-works.com", Phone="967-555-0129" },
            new Customer() { ID=379, LastName="Hanson", FirstName="John", EmailAddress="john20@adventure-works.com", Phone="107-555-0117" },
            new Customer() { ID=380, LastName="Hendricks", FirstName="Valerie", EmailAddress="valerie0@adventure-works.com", Phone="859-555-0140" },
            new Customer() { ID=381, LastName="Henningsen", FirstName="Jay", EmailAddress="jay3@adventure-works.com", Phone="272-555-0126" },
            new Customer() { ID=382, LastName="Henshaw", FirstName="Jeff", EmailAddress="jeff2@adventure-works.com", Phone="1 (11) 500 555-0118" },
            new Customer() { ID=383, LastName="Hensien", FirstName="Kari", EmailAddress="kari0@adventure-works.com", Phone="143-555-0129" },
            new Customer() { ID=384, LastName="Herman", FirstName="Deena", EmailAddress="deena0@adventure-works.com", Phone="1 (11) 500 555-0197" },
            new Customer() { ID=385, LastName="Hernandez", FirstName="Irene", EmailAddress="irene0@adventure-works.com", Phone="790-555-0197" },
            new Customer() { ID=386, LastName="Hernandez", FirstName="Jésus", EmailAddress="jésus0@adventure-works.com", Phone="214-555-0145" },
            new Customer() { ID=387, LastName="Herrick", FirstName="Pam", EmailAddress="pam0@adventure-works.com", Phone="456-555-0184" },
            new Customer() { ID=388, LastName="Herring", FirstName="Cheryl", EmailAddress="cheryl0@adventure-works.com", Phone="158-555-0154" },
            new Customer() { ID=389, LastName="Heymsfield", FirstName="Ronald", EmailAddress="ronald1@adventure-works.com", Phone="784-555-0120" },
            new Customer() { ID=390, LastName="Higa", FirstName="Sidney", EmailAddress="sidney1@adventure-works.com", Phone="215-555-0197" },
            new Customer() { ID=391, LastName="Higgs", FirstName="Onetha", EmailAddress="onetha0@adventure-works.com", Phone="1 (11) 500 555-0178" },
            new Customer() { ID=392, LastName="Highfill", FirstName="Fran", EmailAddress="fran0@adventure-works.com", Phone="117-555-0110" },
            new Customer() { ID=393, LastName="Hill", FirstName="Geneva", EmailAddress="geneva0@adventure-works.com", Phone="1 (11) 500 555-0144" },
            new Customer() { ID=394, LastName="Hill", FirstName="Andrew", EmailAddress="andrew4@adventure-works.com", Phone="194-555-0149" },
            new Customer() { ID=395, LastName="Hillmann", FirstName="Reinout", EmailAddress="reinout1@adventure-works.com", Phone="597-555-0132" },
            new Customer() { ID=396, LastName="Hines", FirstName="Mike", EmailAddress="mike3@adventure-works.com", Phone="454-555-0160" },
            new Customer() { ID=397, LastName="Hink", FirstName="Matthew", EmailAddress="matthew3@adventure-works.com", Phone="146-555-0176" },
            new Customer() { ID=398, LastName="Hirota", FirstName="Nancy", EmailAddress="nancy2@adventure-works.com", Phone="860-555-0119" },
            new Customer() { ID=399, LastName="Hirsch", FirstName="Rose", EmailAddress="rose0@adventure-works.com", Phone="1 (11) 500 555-0157" },
            new Customer() { ID=400, LastName="Hite", FirstName="Douglas", EmailAddress="douglas3@adventure-works.com", Phone="419-555-0166" },
            new Customer() { ID=401, LastName="Hodgson", FirstName="David", EmailAddress="david16@adventure-works.com", Phone="969-555-0117" },
            new Customer() { ID=402, LastName="Hoeing", FirstName="Helge", EmailAddress="helge0@adventure-works.com", Phone="850-555-0198" },
            new Customer() { ID=403, LastName="Hoffman", FirstName="Barbara", EmailAddress="barbara5@adventure-works.com", Phone="140-555-0188" },
            new Customer() { ID=404, LastName="Holt", FirstName="Holly", EmailAddress="holly1@adventure-works.com", Phone="654-555-0150" },
            new Customer() { ID=405, LastName="Hodges", FirstName="Bob", EmailAddress="bob2@adventure-works.com", Phone="129-555-0120" },
            new Customer() { ID=406, LastName="Holloway", FirstName="Jean", EmailAddress="jean2@adventure-works.com", Phone="1 (11) 500 555-0181" },
            new Customer() { ID=407, LastName="Holm", FirstName="Michael", EmailAddress="michael17@adventure-works.com", Phone="1 (11) 500 555-0123" },
            new Customer() { ID=408, LastName="Holmes", FirstName="Eddie", EmailAddress="eddie0@adventure-works.com", Phone="570-555-0199" },
            new Customer() { ID=409, LastName="Holman", FirstName="Juanita", EmailAddress="juanita0@adventure-works.com", Phone="996-555-0196" },
            new Customer() { ID=410, LastName="Houston", FirstName="Peter", EmailAddress="peter3@adventure-works.com", Phone="632-555-0171" },
            new Customer() { ID=411, LastName="Howard", FirstName="Curtis", EmailAddress="curtis0@adventure-works.com", Phone="555-555-0162" },
            new Customer() { ID=412, LastName="Howard", FirstName="Joe", EmailAddress="joe0@adventure-works.com", Phone="1 (11) 500 555-0187" },
            new Customer() { ID=413, LastName="Hows", FirstName="Janice", EmailAddress="janice1@adventure-works.com", Phone="1 (11) 500 555-0119" },
            new Customer() { ID=414, LastName="Huckaby", FirstName="George", EmailAddress="george1@adventure-works.com", Phone="851-555-0127" },
            new Customer() { ID=415, LastName="Huff", FirstName="Joshua", EmailAddress="joshua0@adventure-works.com", Phone="190-555-0186" },
            new Customer() { ID=416, LastName="Huff", FirstName="Arlene", EmailAddress="arlene0@adventure-works.com", Phone="1 (11) 500 555-0146" },
            new Customer() { ID=417, LastName="Hunter", FirstName="Matthew", EmailAddress="matthew4@adventure-works.com", Phone="482-555-0188" },
            new Customer() { ID=418, LastName="Huntsman", FirstName="Phyllis", EmailAddress="phyllis1@adventure-works.com", Phone="153-555-0195" },
            new Customer() { ID=419, LastName="Hurkett", FirstName="Lawrence", EmailAddress="lawrence0@adventure-works.com", Phone="129-555-0185" },
            new Customer() { ID=420, LastName="Ihrig", FirstName="Ryan", EmailAddress="ryan4@adventure-works.com", Phone="809-555-0152" },
            new Customer() { ID=421, LastName="Inghram", FirstName="Beth", EmailAddress="beth0@adventure-works.com", Phone="718-555-0152" },
            new Customer() { ID=422, LastName="Iallo", FirstName="Lucio", EmailAddress="lucio0@adventure-works.com", Phone="199-555-0135" },
            new Customer() { ID=423, LastName="Irwin", FirstName="Richard", EmailAddress="richard4@adventure-works.com", Phone="367-555-0124" },
            new Customer() { ID=424, LastName="Ismert", FirstName="Erik", EmailAddress="erik0@adventure-works.com", Phone="116-555-0163" },
            new Customer() { ID=425, LastName="Ison", FirstName="Denean", EmailAddress="denean0@adventure-works.com", Phone="1 (11) 500 555-0127" },
            new Customer() { ID=426, LastName="Iyer", FirstName="Raman", EmailAddress="raman0@adventure-works.com", Phone="1 (11) 500 555-0112" },
            new Customer() { ID=427, LastName="Jacobs", FirstName="Bronson", EmailAddress="bronson0@adventure-works.com", Phone="697-555-0131" },
            new Customer() { ID=428, LastName="Jacobsen", FirstName="Eric", EmailAddress="eric5@adventure-works.com", Phone="703-555-0120" },
            new Customer() { ID=429, LastName="Jacobson", FirstName="Jodan", EmailAddress="jodan0@adventure-works.com", Phone="652-555-0189" },
            new Customer() { ID=430, LastName="Alexander", FirstName="Mary", EmailAddress="mary7@adventure-works.com", Phone="344-555-0133" },
            new Customer() { ID=431, LastName="Jaffe", FirstName="David", EmailAddress="david17@adventure-works.com", Phone="1 (11) 500 555-0140" },
            new Customer() { ID=432, LastName="Jamison", FirstName="Jay", EmailAddress="jay4@adventure-works.com", Phone="1 (11) 500 555-0113" },
            new Customer() { ID=433, LastName="Johns", FirstName="Vance", EmailAddress="vance0@adventure-works.com", Phone="103-555-0151" },
            new Customer() { ID=434, LastName="Jarvis", FirstName="Joyce", EmailAddress="joyce0@adventure-works.com", Phone="458-555-0179" },
            new Customer() { ID=435, LastName="Jiang", FirstName="George", EmailAddress="george2@adventure-works.com", Phone="1 (11) 500 555-0112" },
            new Customer() { ID=436, LastName="Jiang", FirstName="Stephen", EmailAddress="stephen3@adventure-works.com", Phone="910-555-0116" },
            new Customer() { ID=437, LastName="Johnson", FirstName="Samuel", EmailAddress="samuel1@adventure-works.com", Phone="762-555-0110" },
            new Customer() { ID=438, LastName="Johnson", FirstName="Danielle", EmailAddress="danielle1@adventure-works.com", Phone="356-555-0190" },
            new Customer() { ID=439, LastName="Johnson", FirstName="Greg", EmailAddress="greg3@adventure-works.com", Phone="523-555-0170" },
            new Customer() { ID=440, LastName="Johnson", FirstName="Barry", EmailAddress="barry1@adventure-works.com", Phone="858-555-0140" },
            new Customer() { ID=441, LastName="Johnson", FirstName="Brian", EmailAddress="brian6@adventure-works.com", Phone="320-555-0134" },
            new Customer() { ID=442, LastName="Johnson", FirstName="David", EmailAddress="david18@adventure-works.com", Phone="476-555-0139" },
            new Customer() { ID=443, LastName="Johnson", FirstName="Willis", EmailAddress="willis1@adventure-works.com", Phone="230-555-0164" },
            new Customer() { ID=444, LastName="Johnston", FirstName="Tamara", EmailAddress="tamara0@adventure-works.com", Phone="1 (11) 500 555-0187" },
            new Customer() { ID=445, LastName="Jones", FirstName="Robert", EmailAddress="robert6@adventure-works.com", Phone="595-555-0131" },
            new Customer() { ID=446, LastName="Jones", FirstName="Brannon", EmailAddress="brannon0@adventure-works.com", Phone="895-555-0160" },
            new Customer() { ID=447, LastName="Jordan", FirstName="Jean", EmailAddress="jean3@adventure-works.com", Phone="207-555-0129" },
            new Customer() { ID=448, LastName="Justice", FirstName="Peggy", EmailAddress="peggy0@adventure-works.com", Phone="170-555-0189" },
            new Customer() { ID=449, LastName="Krane", FirstName="Diane", EmailAddress="diane4@adventure-works.com", Phone="224-555-0126" },
            new Customer() { ID=450, LastName="Kaffer", FirstName="Scott", EmailAddress="scott5@adventure-works.com", Phone="1 (11) 500 555-0179" },
            new Customer() { ID=451, LastName="Kitt", FirstName="Sandra", EmailAddress="sandra2@adventure-works.com", Phone="303-555-0117" },
            new Customer() { ID=452, LastName="Kahn", FirstName="Wendy", EmailAddress="wendy1@adventure-works.com", Phone="685-555-0176" },
            new Customer() { ID=453, LastName="Kaliyath", FirstName="Sandeep", EmailAddress="sandeep1@adventure-works.com", Phone="495-555-0113" },
            new Customer() { ID=454, LastName="Kane", FirstName="John", EmailAddress="john21@adventure-works.com", Phone="1 (11) 500 555-0186" },
            new Customer() { ID=455, LastName="Kane", FirstName="Lori", EmailAddress="lori2@adventure-works.com", Phone="765-555-0141" },
            new Customer() { ID=456, LastName="Krane", FirstName="Judith", EmailAddress="judith1@adventure-works.com", Phone="165-555-0172" },
            new Customer() { ID=457, LastName="Krane", FirstName="Kay", EmailAddress="kay0@adventure-works.com", Phone="731-555-0187" },
            new Customer() { ID=458, LastName="Katyal", FirstName="Sandeep", EmailAddress="sandeep2@adventure-works.com", Phone="928-555-0117" },
            new Customer() { ID=459, LastName="Kearney", FirstName="Bonnie", EmailAddress="bonnie1@adventure-works.com", Phone="1 (11) 500 555-0116" },
            new Customer() { ID=460, LastName="Keil", FirstName="Kendall", EmailAddress="kendall1@adventure-works.com", Phone="1 (11) 500 555-0115" },
            new Customer() { ID=461, LastName="Kelley", FirstName="Victor", EmailAddress="victor0@adventure-works.com", Phone="112-555-0195" },
            new Customer() { ID=462, LastName="Kelly", FirstName="John", EmailAddress="john22@adventure-works.com", Phone="330-555-0116" },
            new Customer() { ID=463, LastName="Kelly", FirstName="Robert", EmailAddress="robert7@adventure-works.com", Phone="510-555-0123" },
            new Customer() { ID=464, LastName="Kennedy", FirstName="Kevin", EmailAddress="kevin4@adventure-works.com", Phone="275-555-0179" },
            new Customer() { ID=465, LastName="Kesslep", FirstName="Mary", EmailAddress="mary8@adventure-works.com", Phone="1 (11) 500 555-0146" },
            new Customer() { ID=466, LastName="Kesterson", FirstName="Alice", EmailAddress="alice2@adventure-works.com", Phone="1 (11) 500 555-0132" },
            new Customer() { ID=467, LastName="Keyser", FirstName="Elizabeth", EmailAddress="elizabeth2@adventure-works.com", Phone="656-555-0173" },
            new Customer() { ID=468, LastName="Khan", FirstName="Tammy", EmailAddress="tammy0@adventure-works.com", Phone="145-555-0166" },
            new Customer() { ID=469, LastName="Khan", FirstName="Imtiaz", EmailAddress="imtiaz0@adventure-works.com", Phone="249-555-0179" },
            new Customer() { ID=470, LastName="Khanna", FirstName="Karan", EmailAddress="karan1@adventure-works.com", Phone="390-555-0150" },
            new Customer() { ID=471, LastName="Kim", FirstName="Joe", EmailAddress="joe1@adventure-works.com", Phone="1 (11) 500 555-0144" },
            new Customer() { ID=472, LastName="Kim", FirstName="Jim", EmailAddress="jim2@adventure-works.com", Phone="1 (11) 500 555-0165" },
            new Customer() { ID=473, LastName="Kim", FirstName="Shane", EmailAddress="shane2@adventure-works.com", Phone="155-555-0149" },
            new Customer() { ID=474, LastName="Kim", FirstName="Tim", EmailAddress="tim0@adventure-works.com", Phone="244-555-0115" },
            new Customer() { ID=475, LastName="King", FirstName="Russell", EmailAddress="russell2@adventure-works.com", Phone="871-555-0159" },
            new Customer() { ID=476, LastName="Kirilov", FirstName="Anton", EmailAddress="anton0@adventure-works.com", Phone="608-555-0162" },
            new Customer() { ID=477, LastName="Kleinerman", FirstName="Christian", EmailAddress="christian1@adventure-works.com", Phone="362-555-0177" },
            new Customer() { ID=478, LastName="Kobylinski", FirstName="Andrew", EmailAddress="andrew5@adventure-works.com", Phone="129-555-0185" },
            new Customer() { ID=479, LastName="Koch", FirstName="Reed", EmailAddress="reed1@adventure-works.com", Phone="108-555-0171" },
            new Customer() { ID=480, LastName="Kennedy", FirstName="Jim", EmailAddress="jim3@adventure-works.com", Phone="1 (11) 500 555-0199" },
            new Customer() { ID=481, LastName="King", FirstName="Kirk", EmailAddress="kirk2@adventure-works.com", Phone="979-555-0163" },
            new Customer() { ID=482, LastName="Kogan", FirstName="Eugene", EmailAddress="eugene2@adventure-works.com", Phone="136-555-0134" },
            new Customer() { ID=483, LastName="Konersmann", FirstName="Scott", EmailAddress="scott6@adventure-works.com", Phone="556-555-0192" },
            new Customer() { ID=484, LastName="Koski", FirstName="Joy", EmailAddress="joy0@adventure-works.com", Phone="810-555-0198" },
            new Customer() { ID=485, LastName="Kotc", FirstName="Pamala", EmailAddress="pamala0@adventure-works.com", Phone="1 (11) 500 555-0173" },
            new Customer() { ID=486, LastName="Kozlowski", FirstName="Edward", EmailAddress="edward1@adventure-works.com", Phone="1 (11) 500 555-0170" },
            new Customer() { ID=487, LastName="Kramer", FirstName="James", EmailAddress="james10@adventure-works.com", Phone="814-555-0130" },
            new Customer() { ID=488, LastName="Kennedy", FirstName="Mitch", EmailAddress="mitch0@adventure-works.com", Phone="996-555-0192" },
            new Customer() { ID=489, LastName="Krow", FirstName="James", EmailAddress="james11@adventure-works.com", Phone="265-555-0190" },
            new Customer() { ID=490, LastName="Krupka", FirstName="Margaret", EmailAddress="margaret1@adventure-works.com", Phone="107-555-0132" },
            new Customer() { ID=491, LastName="Kumar", FirstName="Deepak", EmailAddress="deepak0@adventure-works.com", Phone="1 (11) 500 555-0122" },
            new Customer() { ID=492, LastName="Kung", FirstName="Jeffrey", EmailAddress="jeffrey2@adventure-works.com", Phone="1 (11) 500 555-0127" },
            new Customer() { ID=493, LastName="Kuppa", FirstName="Vamsi", EmailAddress="vamsi1@adventure-works.com", Phone="290-555-0196" },
            new Customer() { ID=494, LastName="Kurtz", FirstName="Jeffrey", EmailAddress="jeffrey3@adventure-works.com", Phone="452-555-0179" },
            new Customer() { ID=495, LastName="Kurniawan", FirstName="Peter", EmailAddress="peter4@adventure-works.com", Phone="436-555-0160" },
            new Customer() { ID=496, LastName="Lang", FirstName="Eric", EmailAddress="eric6@adventure-works.com", Phone="932-555-0163" },
            new Customer() { ID=497, LastName="Laszlo", FirstName="Rebecca", EmailAddress="rebecca2@adventure-works.com", Phone="1 (11) 500 555-0155" },
            new Customer() { ID=498, LastName="Laursen", FirstName="Cecilia", EmailAddress="cecilia0@adventure-works.com", Phone="1 (11) 500 555-0181" },
            new Customer() { ID=499, LastName="Lawrence", FirstName="David", EmailAddress="david19@adventure-works.com", Phone="653-555-0159" },
            new Customer() { ID=500, LastName="Leavitt", FirstName="Elsa", EmailAddress="elsa0@adventure-works.com", Phone="482-555-0174" }
        };

        [Queryable]
        public override IQueryable<Customer> Get()
        {
            return customers.AsQueryable();
        }

        protected override Customer GetEntityByKey(int Id)
        {
            return (from c in customers where c.ID == Id select c).FirstOrDefault();
        }
    }
}
