//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;activityFeed xmlns=&quot;http://schemas.microsoft.com/office/outlook/socialprovider.xsd&quot;&gt;
        ///  &lt;network&gt;Contoso&lt;/network&gt;
        ///  &lt;activities&gt;
        ///    &lt;activityDetails&gt;
        ///      &lt;ownerID&gt;4667647&lt;/ownerID&gt;
        ///      &lt;objectID&gt;9d2b5e6360894a21d56d7d0b5969d23cf4034a31&lt;/objectID&gt;
        ///      &lt;applicationID&gt;2&lt;/applicationID&gt;
        ///      &lt;templateID&gt;1&lt;/templateID&gt;
        ///      &lt;publishDate&gt;2010-03-05T17:19:57&lt;/publishDate&gt;
        ///      &lt;templateVariables&gt;
        ///        &lt;templateVariable type=&quot;publisherVariable&quot;&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string activityFeed {
            get {
                return ResourceManager.GetString("activityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; ?&gt;
        ///&lt;capabilities xmlns=&quot;http://schemas.microsoft.com/office/outlook/socialprovider.xsd&quot;&gt;
        ///  &lt;getFriends&gt;true&lt;/getFriends&gt;
        ///  &lt;cacheFriends&gt;true&lt;/cacheFriends&gt;
        ///  &lt;followPerson&gt;true&lt;/followPerson&gt;
        ///  &lt;doNotFollowPerson&gt;false&lt;/doNotFollowPerson&gt;
        ///  &lt;getActivities&gt;true&lt;/getActivities&gt;
        ///  &lt;cacheActivities&gt;true&lt;/cacheActivities&gt;
        ///  &lt;dynamicActivitiesLookup&gt;false&lt;/dynamicActivitiesLookup&gt;
        ///  &lt;displayUrl&gt;false&lt;/displayUrl&gt;
        ///  &lt;useLogonWebAuth&gt;false&lt;/useLogonWebAuth&gt;
        ///  &lt;hideH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string capabilities {
            get {
                return ResourceManager.GetString("capabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;person&gt;
        ///  &lt;userID&gt;4667647&lt;/userID&gt;
        ///  &lt;firstName&gt;Melissa&lt;/firstName&gt;
        ///  &lt;lastName&gt;MacBeth&lt;/lastName&gt;
        ///  &lt;nickname&gt;&lt;/nickname&gt;
        ///  &lt;fileAs&gt;MacBeth, Melissa (Contoso Ltd.)&lt;/fileAs&gt;
        ///  &lt;company&gt;Contoso Ltd.&lt;/company&gt;
        ///  &lt;title&gt;Product Manager&lt;/title&gt;
        ///  &lt;anniversary&gt;2005-05-17&lt;/anniversary&gt;
        ///  &lt;birthday&gt;1979-08-09&lt;/birthday&gt;
        ///  &lt;emailAddress&gt;melissa@contoso.com&lt;/emailAddress&gt;
        ///  &lt;emailAddress2&gt;melissa@fabrikam.com&lt;/emailAddress2&gt;
        ///  &lt;emailAddress3&gt;melissa@adventureworks.com&lt;/emailAddress3&gt;
        ///  &lt;webProfilePage&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string friend1 {
            get {
                return ResourceManager.GetString("friend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;person&gt;
        ///  &lt;userID&gt;5015012&lt;/userID&gt;
        ///  &lt;firstName&gt;Michael&lt;/firstName&gt;
        ///  &lt;lastName&gt;Affronti&lt;/lastName&gt;
        ///  &lt;nickname&gt;Mr. Social&lt;/nickname&gt;
        ///  &lt;fileAs&gt;Affronti, Michael (Contoso Ltd.)&lt;/fileAs&gt;
        ///  &lt;company&gt;Contoso Ltd.&lt;/company&gt;
        ///  &lt;title&gt;Sales Director&lt;/title&gt;
        ///  &lt;anniversary&gt;2009-06-21&lt;/anniversary&gt;
        ///  &lt;birthday&gt;1980-09-10&lt;/birthday&gt;
        ///  &lt;emailAddress&gt;michael@contoso.com&lt;/emailAddress&gt;
        ///  &lt;emailAddress2&gt;michael@fabrikam.com&lt;/emailAddress2&gt;
        ///  &lt;emailAddress3&gt;michael@adventureworks.com&lt;/emailAddress3&gt;
        ///  &lt;webP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string friend2 {
            get {
                return ResourceManager.GetString("friend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;friends xmlns=&quot;http://schemas.microsoft.com/office/outlook/socialprovider.xsd&quot;&gt;
        ///  &lt;person&gt;
        ///    &lt;userID&gt;4667647&lt;/userID&gt;
        ///    &lt;firstName&gt;Melissa&lt;/firstName&gt;
        ///    &lt;lastName&gt;MacBeth&lt;/lastName&gt;
        ///    &lt;nickname&gt;&lt;/nickname&gt;
        ///    &lt;fileAs&gt;MacBeth, Melissa (Contoso Ltd.)&lt;/fileAs&gt;
        ///    &lt;company&gt;Contoso Ltd.&lt;/company&gt;
        ///    &lt;title&gt;Product Manager&lt;/title&gt;
        ///    &lt;anniversary&gt;2005-05-17&lt;/anniversary&gt;
        ///    &lt;birthday&gt;1979-08-09&lt;/birthday&gt;
        ///    &lt;emailAddress&gt;melissa@contoso.com&lt;/emai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Penguins {
            get {
                object obj = ResourceManager.GetObject("Penguins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap testprovider {
            get {
                object obj = ResourceManager.GetObject("testprovider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
