/// <reference path="jquery-1.8.2.js" />
/// <reference name="MicrosoftAjax.js" />
/// <reference path="~/_layouts/15/init.js" />
/// <reference path="~/_layouts/15/SP.Core.js" />
/// <reference path="~/_layouts/15/SP.Runtime.js" />
/// <reference path="~/_layouts/15/SP.UI.Dialog.js" />
/// <reference path="~/_layouts/15/SP.js" />
/// <reference path="wingtip.stickynote.js" />
/// <reference path="wingtip.viewmodel.js" />
/// <reference path="knockout-2.2.1.debug.js"/>
