//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SAPSK.ContosoTours.SAPServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTAVAILIBILITY_BAPI_FLIGHT_CHECKAVAILIBILITYService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTAVAILIBILITY_BAPI_FLIGHT_CHECKAVAILIBILITYServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTCUSTOMERCREATE_BAPI_FLCUST_CREATEFROMDATAService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTCUSTOMERCREATE_BAPI_FLCUST_CREATEFROMDATAServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTCUSTOMERLIST_BAPI_FLCUST_GETLISTService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTCUSTOMERLIST_BAPI_FLCUST_GETLISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTLIST_BAPI_FLIGHT_GETLISTService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTLIST_BAPI_FLIGHT_GETLISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTCONNLIST_BAPI_FLCONN_GETLISTService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTCONNLIST_BAPI_FLCONN_GETLISTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTCONNDETAIL_BAPI_FLCONN_GETDETAILService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTCONNDETAIL_BAPI_FLCONN_GETDETAILService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_COMMITWORK_BAPI_TRANSACTION_COMMITService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_COMMITWORK_BAPI_TRANSACTION_COMMITService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTTRIPCREATE_BAPI_FLTRIP_CREATEService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTTRIPCREATE_BAPI_FLTRIP_CREATEService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8000/sap/bc/soap/rfc")]
        public string ContosoTours_SAPServices_SAP_FLIGHTTRIPLIST_BAPI_FLTRIP_GETLISTService {
            get {
                return ((string)(this["ContosoTours_SAPServices_SAP_FLIGHTTRIPLIST_BAPI_FLTRIP_GETLISTService"]));
            }
        }
    }
}
